/* ─── Business type → template + default content mapping ─── */

export type BusinessType = {
  id: string;
  label: string;
  templateSlug: string;
  defaultContent: Record<string, string>;
};

export const BUSINESS_TYPES: BusinessType[] = [
  {
    id: "saude-terapia",
    label: "Saúde e Terapia",
    templateSlug: "essencia",
    defaultContent: {
      heroEyebrow: "Cuidado que transforma",
      heroTitle: "Seu bem-estar começa aqui",
      heroSubtitle: "Atendimento humanizado e personalizado para você encontrar equilíbrio e saúde.",
      heroCtaLabel: "Agendar consulta",
      servicesTitle: "Como posso te ajudar",
      ctaTitle: "Pronto para cuidar de você?",
      ctaDescription: "Agende uma consulta e dê o primeiro passo para o seu bem-estar.",
      ctaButtonLabel: "Falar comigo",
      aboutTitle: "Sobre mim",
      aboutDescription: "Profissional dedicada a oferecer cuidado integral e personalizado, com anos de experiência ajudando pessoas a alcançarem saúde e equilíbrio.",
    },
  },
  {
    id: "beleza-estetica",
    label: "Beleza e Estética",
    templateSlug: "essencia",
    defaultContent: {
      heroEyebrow: "Realce sua beleza",
      heroTitle: "Beleza que eleva a autoestima",
      heroSubtitle: "Tratamentos especializados para você se sentir radiante e confiante todos os dias.",
      heroCtaLabel: "Agendar horário",
      servicesTitle: "Nossos tratamentos",
      ctaTitle: "Pronta para se transformar?",
      ctaDescription: "Agende seu horário e cuide da sua autoestima com quem entende.",
      ctaButtonLabel: "Reservar agora",
      aboutTitle: "Nossa história",
      aboutDescription: "Especialistas em beleza e estética, comprometidos em oferecer os melhores tratamentos com produtos de alta qualidade.",
    },
  },
  {
    id: "nutricao-alimentacao",
    label: "Nutrição e Alimentação",
    templateSlug: "broto",
    defaultContent: {
      heroEyebrow: "Alimentação saudável",
      heroTitle: "Transforme sua relação com a comida",
      heroSubtitle: "Orientação nutricional personalizada para você ter mais saúde, energia e qualidade de vida.",
      heroCtaLabel: "Marcar consulta",
      servicesTitle: "Meus serviços",
      ctaTitle: "Comece sua jornada saudável",
      ctaDescription: "Agende sua consulta e descubra o plano alimentar ideal para você.",
      ctaButtonLabel: "Quero me cuidar",
      aboutTitle: "Sobre mim",
      aboutDescription: "Nutricionista apaixonada por ajudar pessoas a alcançarem saúde e bem-estar através de uma alimentação equilibrada e prazerosa.",
    },
  },
  {
    id: "yoga-meditacao",
    label: "Yoga e Meditação",
    templateSlug: "broto",
    defaultContent: {
      heroEyebrow: "Equilíbrio e paz interior",
      heroTitle: "Encontre seu centro",
      heroSubtitle: "Práticas de yoga e meditação para cultivar equilíbrio, presença e bem-estar no dia a dia.",
      heroCtaLabel: "Começar agora",
      servicesTitle: "Práticas e modalidades",
      ctaTitle: "Inicie sua jornada interior",
      ctaDescription: "Experimente uma aula experimental e sinta a diferença na sua vida.",
      ctaButtonLabel: "Aula experimental",
      aboutTitle: "Minha prática",
      aboutDescription: "Instrutora certificada com mais de 8 anos de experiência, guiando alunos em suas jornadas de autoconhecimento e bem-estar.",
    },
  },
  {
    id: "fitness-academia",
    label: "Fitness e Academia",
    templateSlug: "faisca",
    defaultContent: {
      heroEyebrow: "Resultados reais",
      heroTitle: "Supere seus limites",
      heroSubtitle: "Treinos personalizados e acompanhamento profissional para você alcançar seus objetivos.",
      heroCtaLabel: "Começar treinar",
      servicesTitle: "Nossos programas",
      ctaTitle: "Pronto para mudar?",
      ctaDescription: "Faça uma aula experimental e sinta a diferença do treino certo.",
      ctaButtonLabel: "Aula grátis",
      aboutTitle: "Nossa academia",
      aboutDescription: "Ambiente motivador com equipamentos modernos e profissionais qualificados para te ajudar a alcançar seu melhor físico.",
    },
  },
  {
    id: "servicos-gerais",
    label: "Serviços Gerais",
    templateSlug: "faisca",
    defaultContent: {
      heroEyebrow: "Serviços de qualidade",
      heroTitle: "A solução que você precisa",
      heroSubtitle: "Atendimento rápido, qualidade garantida e preço justo. Conte com a gente para resolver.",
      heroCtaLabel: "Pedir orçamento",
      servicesTitle: "O que fazemos",
      ctaTitle: "Vamos trabalhar juntos?",
      ctaDescription: "Entre em contato e receba um orçamento sem compromisso.",
      ctaButtonLabel: "Orçamento grátis",
      aboutTitle: "Quem somos",
      aboutDescription: "Empresa comprometida com qualidade e satisfação do cliente, oferecendo serviços confiáveis e eficientes.",
    },
  },
  {
    id: "design-criacao",
    label: "Design e Criação",
    templateSlug: "quadro",
    defaultContent: {
      heroEyebrow: "Design com propósito",
      heroTitle: "Visualmente impecável",
      heroSubtitle: "Criação de identidades visuais, materiais gráficos e experiências digitais que conectam marcas e pessoas.",
      heroCtaLabel: "Ver portfólio",
      servicesTitle: "Serviços criativos",
      ctaTitle: "Vamos criar algo incrível?",
      ctaDescription: "Fale sobre seu projeto e descubra como posso transformar sua visão em realidade.",
      ctaButtonLabel: "Iniciar projeto",
      aboutTitle: "Sobre o estúdio",
      aboutDescription: "Estúdio criativo especializado em design estratégico e identidade visual, com portfólio de marcas em todo o Brasil.",
    },
  },
  {
    id: "fotografia-arte",
    label: "Fotografia e Arte",
    templateSlug: "quadro",
    defaultContent: {
      heroEyebrow: "Momentos eternizados",
      heroTitle: "Arte que conta histórias",
      heroSubtitle: "Fotografia profissional para guardar cada momento especial com a qualidade que merece.",
      heroCtaLabel: "Ver trabalhos",
      servicesTitle: "Tipos de sessão",
      ctaTitle: "Vamos criar memórias?",
      ctaDescription: "Agende sua sessão e eternize os momentos mais importantes da sua vida.",
      ctaButtonLabel: "Reservar sessão",
      aboutTitle: "Sobre mim",
      aboutDescription: "Fotógrafo apaixonado por contar histórias através de imagens, com olhar artístico e técnica refinada para cada projeto.",
    },
  },
  {
    id: "musica-entretenimento",
    label: "Música e Entretenimento",
    templateSlug: "cena",
    defaultContent: {
      heroEyebrow: "Experiências únicas",
      heroTitle: "Música que emociona",
      heroSubtitle: "Shows, eventos e produções musicais que transformam qualquer ocasião em uma experiência inesquecível.",
      heroCtaLabel: "Ver agenda",
      servicesTitle: "Shows e eventos",
      ctaTitle: "Quer uma experiência única?",
      ctaDescription: "Entre em contato para verificar disponibilidade e fazer uma proposta.",
      ctaButtonLabel: "Contratar",
      aboutTitle: "Sobre o artista",
      aboutDescription: "Músico profissional com trajetória consolidada, unindo talento e técnica para criar performances memoráveis.",
    },
  },
  {
    id: "coaching-desenvolvimento",
    label: "Coaching e Desenvolvimento",
    templateSlug: "sinal",
    defaultContent: {
      heroEyebrow: "Transformação real",
      heroTitle: "Desbloqueie seu potencial",
      heroSubtitle: "Processo de coaching estruturado para você alcançar clareza, foco e resultados extraordinários.",
      heroCtaLabel: "Sessão gratuita",
      servicesTitle: "Programas de desenvolvimento",
      ctaTitle: "Pronto para se transformar?",
      ctaDescription: "Agende uma sessão estratégica gratuita e descubra seu próximo passo.",
      ctaButtonLabel: "Quero evoluir",
      aboutTitle: "Minha metodologia",
      aboutDescription: "Coach certificado com metodologia comprovada, ajudando profissionais e empresas a alcançarem seu máximo potencial.",
    },
  },
  {
    id: "educacao-cursos",
    label: "Educação e Cursos",
    templateSlug: "sinal",
    defaultContent: {
      heroEyebrow: "Conhecimento que transforma",
      heroTitle: "Aprenda com quem entende",
      heroSubtitle: "Cursos e treinamentos práticos para você desenvolver habilidades e avançar na carreira.",
      heroCtaLabel: "Ver cursos",
      servicesTitle: "Nossos cursos",
      ctaTitle: "Comece a aprender hoje",
      ctaDescription: "Escolha seu curso e dê o próximo passo na sua carreira.",
      ctaButtonLabel: "Quero aprender",
      aboutTitle: "Nossa metodologia",
      aboutDescription: "Educadores comprometidos com aprendizado prático e resultados reais, com mais de 500 alunos formados.",
    },
  },
  {
    id: "tecnologia-ti",
    label: "Tecnologia e TI",
    templateSlug: "codigo",
    defaultContent: {
      heroEyebrow: "Soluções em tecnologia",
      heroTitle: "Tecnologia que resolve",
      heroSubtitle: "Desenvolvimento, consultoria e suporte em TI para sua empresa funcionar com máxima eficiência.",
      heroCtaLabel: "Falar com especialista",
      servicesTitle: "Nossas soluções",
      ctaTitle: "Pronto para escalar?",
      ctaDescription: "Fale com nossa equipe e descubra como podemos acelerar seu negócio com tecnologia.",
      ctaButtonLabel: "Solicitar proposta",
      aboutTitle: "Nossa expertise",
      aboutDescription: "Time de especialistas em tecnologia com foco em entregar soluções sob medida para negócios em crescimento.",
    },
  },
  {
    id: "juridico-advocacia",
    label: "Jurídico e Advocacia",
    templateSlug: "estrutura",
    defaultContent: {
      heroEyebrow: "Segurança jurídica",
      heroTitle: "Seus direitos protegidos",
      heroSubtitle: "Assessoria jurídica especializada para proteger você e seu negócio com seriedade e competência.",
      heroCtaLabel: "Consulta inicial",
      servicesTitle: "Áreas de atuação",
      ctaTitle: "Precisa de assessoria jurídica?",
      ctaDescription: "Agende uma consulta e entenda como podemos proteger seus interesses.",
      ctaButtonLabel: "Agendar consulta",
      aboutTitle: "O escritório",
      aboutDescription: "Escritório de advocacia com atuação especializada e comprometimento com a defesa dos direitos dos nossos clientes.",
    },
  },
  {
    id: "financas-contabilidade",
    label: "Finanças e Contabilidade",
    templateSlug: "estrutura",
    defaultContent: {
      heroEyebrow: "Organização financeira",
      heroTitle: "Suas finanças em ordem",
      heroSubtitle: "Contabilidade, consultoria financeira e planejamento tributário para sua empresa crescer com segurança.",
      heroCtaLabel: "Consultoria grátis",
      servicesTitle: "Serviços contábeis",
      ctaTitle: "Organize suas finanças hoje",
      ctaDescription: "Agende uma consulta gratuita e descubra como otimizar sua gestão financeira.",
      ctaButtonLabel: "Falar com contador",
      aboutTitle: "Nossa equipe",
      aboutDescription: "Contadores e consultores financeiros dedicados a oferecer soluções seguras e estratégicas para o crescimento do seu negócio.",
    },
  },
  {
    id: "outro",
    label: "Outro",
    templateSlug: "sinal",
    defaultContent: {
      heroEyebrow: "Bem-vindo",
      heroTitle: "O que fazemos melhor",
      heroSubtitle: "Serviços de qualidade e atendimento personalizado para superar suas expectativas.",
      heroCtaLabel: "Saiba mais",
      servicesTitle: "Nossos serviços",
      ctaTitle: "Vamos conversar?",
      ctaDescription: "Entre em contato e descubra como podemos ajudar você.",
      ctaButtonLabel: "Entrar em contato",
      aboutTitle: "Sobre nós",
      aboutDescription: "Equipe comprometida em oferecer o melhor serviço com qualidade e dedicação.",
    },
  },
];

export function getBusinessTypeById(id: string): BusinessType | undefined {
  return BUSINESS_TYPES.find((bt) => bt.id === id);
}

export function getTemplateForBusinessType(businessTypeId: string): string {
  return getBusinessTypeById(businessTypeId)?.templateSlug ?? "sinal";
}

export function getDefaultContentForBusinessType(businessTypeId: string): Record<string, string> {
  return getBusinessTypeById(businessTypeId)?.defaultContent ?? {};
}
